name: docker-image-cicd

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    tags:
      - 'v*'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

jobs:
  docker-multiarch:
    uses: vionix-proj/shared-workflows/.github/workflows/docker-multiarch-cicd.yaml@main
    with:
      registry: ghcr.io
      platforms: linux/amd64,linux/arm64
      docker-compose-file-name: docker-compose.yaml
      dockerhub-registry: docker.io
      dockerhub-namespace: ${{ github.repository_owner }}
      dockerhub-registry-username: ${{ env.DOCKERHUB_USERNAME }}
      dockerhub-registry-token: ${{ env.DOCKERHUB_USERNAME }}
      push-attestations: "false"
    secrets: inherit
